


const languages = [

    { "label": "Amharic" },
    { "label": "Arabic" },
    { "label": "Basque" },
    { "label": "Bengali" },
    { "label": "English (UK)" },
    { "label": "Portuguese (Brazil)" },
    { "label": "Bulgarian" },
    { "label": "Catalan" },
    { "label": "Cherokee" },
    { "label": "Croatian" },
    { "label": "Czech" },
    { "label": "Danish" },
    { "label": "Dutch" },
    { "label": "English (US)" },
    { "label": "Estonian" },
    { "label": "Filipino" },
    { "label": "Finnish" },
    { "label": "French" },
    { "label": "German" },
    { "label": "Greek" },
    { "label": "Gujarati" },
    { "label": "Hebrew" },
    { "label": "Hindi" },
    { "label": "Hungarian" },
    { "label": "Icelandic" },
    { "label": "Indonesian" },
    { "label": "Italian" },
    { "label": "Japanese" },
    { "label": "Kannada" },
    { "label": "Korean" },
    { "label": "Latvian" },
    { "label": "Lithuanian" },
    { "label": "Malay" },
    { "label": "Malayalam" },
    { "label": "Marathi" },
    { "label": "Norwegian" },
    { "label": "Polish" },
    { "label": "Portuguese (Portugal)" },
    { "label": "Romanian" },
    { "label": "Russian" },
    { "label": "Serbian" },
    { "label": "Chinese (PRC)" },
    { "label": "Slovak" },
    { "label": "Slovenian" },
    { "label": "Spanish" },
    { "label": "Swahili" },
    { "label": "Swedish" },
    { "label": "Tamil" },
    { "label": "Telugu" },
    { "label": "Thai" },
    { "label": "Chinese (Taiwan)" },
    { "label": "Turkish" },
    { "label": "Urdu" },
    { "label": "Ukrainian" },
    { "label": "Vietnamese" },
    { "label": "Welsh" }
]




export default languages;