const languages = [
    { label: "Amharic", code: "am" },
    { label: "Arabic", code: "ar" },
    { label: "Basque", code: "eu" },
    { label: "Bengali", code: "bn" },
    { label: "English (UK)", code: "en-GB" },
    { label: "Portuguese (Brazil)", code: "pt-BR" },
    { label: "Bulgarian", code: "bg" },
    { label: "Catalan", code: "ca" },
    { label: "Cherokee", code: "chr" },
    { label: "Croatian", code: "hr" },
    { label: "Czech", code: "cs" },
    { label: "Danish", code: "da" },
    { label: "Dutch", code: "nl" },
    { label: "English (US)", code: "en-US" },
    { label: "Estonian", code: "et" },
    { label: "Filipino", code: "fil" },
    { label: "Finnish", code: "fi" },
    { label: "French", code: "fr" },
    { label: "German", code: "de" },
    { label: "Greek", code: "el" },
    { label: "Gujarati", code: "gu" },
    { label: "Hebrew", code: "he" },
    { label: "Hindi", code: "hi" },
    { label: "Hungarian", code: "hu" },
    { label: "Icelandic", code: "is" },
    { label: "Indonesian", code: "id" },
    { label: "Italian", code: "it" },
    { label: "Japanese", code: "ja" },
    { label: "Kannada", code: "kn" },
    { label: "Korean", code: "ko" },
    { label: "Latvian", code: "lv" },
    { label: "Lithuanian", code: "lt" },
    { label: "Malay", code: "ms" },
    { label: "Malayalam", code: "ml" },
    { label: "Marathi", code: "mr" },
    { label: "Norwegian", code: "no" },
    { label: "Polish", code: "pl" },
    { label: "Portuguese (Portugal)", code: "pt-PT" },
    { label: "Romanian", code: "ro" },
    { label: "Russian", code: "ru" },
    { label: "Serbian", code: "sr" },
    { label: "Chinese (PRC)", code: "zh-CN" },
    { label: "Slovak", code: "sk" },
    { label: "Slovenian", code: "sl" },
    { label: "Spanish", code: "es" },
    { label: "Swahili", code: "sw" },
    { label: "Swedish", code: "sv" },
    { label: "Tamil", code: "ta" },
    { label: "Telugu", code: "te" },
    { label: "Thai", code: "th" },
    { label: "Chinese (Taiwan)", code: "zh-TW" },
    { label: "Turkish", code: "tr" },
    { label: "Urdu", code: "ur" },
    { label: "Ukrainian", code: "uk" },
    { label: "Vietnamese", code: "vi" },
    { label: "Welsh", code: "cy" }
];

export default languages;